// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdj2sd40fNluYnPXHbKfp6CInjn0b4aeQ',
    appId: '1:360174944987:android:6df5a9b8b17542ce6502fe',
    messagingSenderId: '360174944987',
    projectId: 'fitsy-af0239',
    storageBucket: 'fitsy-af0239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPwe6wlBzJZPyzhkEJHU-t3Gx1-ZccQqw',
    appId: '1:360174944987:ios:1bb9f7b42ec698bc6502fe',
    messagingSenderId: '360174944987',
    projectId: 'fitsy-af0239',
    storageBucket: 'fitsy-af0239.firebasestorage.app',
    iosBundleId: 'com.fitsy.fitsy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPSM6qdh2vLRVGnU4ek4gN-HSdswiKSDc',
    appId: '1:360174944987:web:c04e05f7367aab536502fe',
    messagingSenderId: '360174944987',
    projectId: 'fitsy-af0239',
    authDomain: 'fitsy-af0239.firebaseapp.com',
    storageBucket: 'fitsy-af0239.firebasestorage.app',
  );

}